src/Entity/Author.php
<?php

namespace App\Entity;

use App\Repository\AuthorRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AuthorRepository::class)]
class Author
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $username = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column]
    private ?int $nb_books = null;

    /**
     * @var Collection<int, Book>
     */
    #[ORM\OneToMany(targetEntity: Book::class, mappedBy: 'author')]
    private Collection $books;

    public function __construct()
    {
        $this->books = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getNbBooks(): ?int
    {
        return $this->nb_books;
    }

    public function setNbBooks(int $nb_books): static
    {
        $this->nb_books = $nb_books;

        return $this;
    }

    /**
     * @return Collection<int, Book>
     */
    public function getBooks(): Collection
    {
        return $this->books;
    }

    public function addBook(Book $book): static
    {
        if (!$this->books->contains($book)) {
            $this->books->add($book);
            $book->setAuthor($this);
        }

        return $this;
    }

    public function removeBook(Book $book): static
    {
        if ($this->books->removeElement($book)) {
            // set the owning side to null (unless already changed)
            if ($book->getAuthor() === $this) {
                $book->setAuthor(null);
            }
        }

        return $this;
    }
}

src/Form/AuthorType.php
<?php

namespace App\Form;

use App\Entity\Author;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AuthorType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username')
            ->add('email')
            ->add('nb_books')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Author::class,
        ]);
    }
}

src/Controller/AuthorController.php
<?php

namespace App\Controller;

use App\Form\AuthorType;
use App\Repository\AuthorRepository;
use App\Repository\BookRepository;
use Doctrine\Persistence\ManagerRegistry;
use App\Entity\Author;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class AuthorController extends AbstractController
{
    #[Route('/author', name: 'app_author')]
    public function index(AuthorRepository $authorRepository, BookRepository $bookRepository): Response
    {
        $authors = $authorRepository->findAll();
        $numberOfPublishedBooks = $bookRepository->count(['published' => true]);
        $numberOfUnPublishedBooks = $bookRepository->count(['published' => false]);
        return $this->render('author/index.html.twig', [
            'authors' => $authors,
            'nb_published' => $numberOfPublishedBooks,
            'nb_unpublished' => $numberOfUnPublishedBooks
        ]);
    }
    #[Route('/author/Add', name: 'author_new')]
    public function new(Request $request, ManagerRegistry $managerRegistry): Response
    {
        $author = new Author();

        $form = $this->createForm(AuthorType::class, $author);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $e = $managerRegistry->getManager();
            $e->persist($author);
            $e->flush();

            return $this->redirectToRoute('app_success');
        }

        return $this->render('author/new.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    #[Route('/author/success', name: 'app_success')]
    public function successAdd() : Response
    {
        return $this->render('author/success.html.twig');
    }
    #[Route('/author/edit/{id}', name: 'author_edit')]
    public function edit(Request $request, Author $author, ManagerRegistry $managerRegistry): Response
    {
        $form = $this->createForm(AuthorType::class, $author);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $e = $managerRegistry->getManager();
            $e->persist($author);
            $e->flush();

            return $this->redirectToRoute('app_author');
        }

        return $this->render('author/edit.html.twig',[
            'form' => $form->createView(),
            'author' => $author,
        ]);
    }
    #[Route('/author/delete/{id}', name: 'author_delete')]
    public function delete(Request $request, Author $author, ManagerRegistry $managerRegistry): Response
    {
        if ($this->isCsrfTokenValid('delete' . $author->getId(), $request->request->get('_token')))
        {
            $e = $managerRegistry->getManager();
            $e->remove($author);
            $e->flush();
        }
        return $this->redirectToRoute('app_author');
    }
    #[Route('/author/minmax',name: 'authorMinMax')]
    public function minMax(Request $request, AuthorRepository $authorRepository, BookRepository $bookRepository) : Response
    {
        $min = $request->get('min');
        $max = $request->get('max');

        $authors = $authorRepository->minMaxnbBooks($min,$max);

        $numberOfPublishedBooks = $bookRepository->count(['published' => true]);
        $numberOfUnPublishedBooks = $bookRepository->count(['published' => false]);
        return $this->render('author/index.html.twig', [
            'authors' => $authors,
            'nb_published' => $numberOfPublishedBooks,
            'nb_unpublished' => $numberOfUnPublishedBooks
        ]);

    }

    #[Route('/author/deletezero', name : 'deleteZeroBooks')]
    public function deleteZeroBooks(AuthorRepository $authorRepository) : Response {

        $authorRepository->deleteZeroBooks();

        return $this->redirectToRoute('app_author');
    }

    #[Route('/author/listbyemail', name : 'listEmail')]
    public function listEmail(AuthorRepository $authorRepository, BookRepository $bookRepository) : Response {

        $authors = $authorRepository->listAuthorsByEmail();

        $numberOfPublishedBooks = $bookRepository->count(['published' => true]);
        $numberOfUnPublishedBooks = $bookRepository->count(['published' => false]);        

        return $this->render('author/index.html.twig', [
            'authors' => $authors,
            'nb_published' => $numberOfPublishedBooks,
            'nb_unpublished' => $numberOfUnPublishedBooks
        ]);
    }
    
}

templates/author/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add a new author{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="mb-4">Edit</h1>

        {{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'novalidate'}}) }}
        <div class="form-group row mb-3">
            {{ form_label(form.username, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
            <div class="col-sm-10">
                {{ form_widget(form.username, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="form-group row mb-3">
            {{ form_label(form.email, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
            <div class="col-sm-10">
                {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="form-group row mb-3">
            {{ form_label(form.nb_books, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
            <div class="col-sm-10">
                {{ form_widget(form.nb_books, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Save changes</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/author/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Authors list{% endblock %}

{% block body %}
    <div class="container mt-5">
        {% if authors is empty %}
            <div class="alert alert-warning" role="alert">
                No Authors found
            </div>
            <a href="{{ path('author_new') }}" class="btn btn-primary">Click here to add a new author</a>
        {% else %}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Email</th>
                    <th>Number of Books</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for author in authors %}
                    <tr>
                        <td>{{ author.id }}</td>
                        <td>{{ author.username }}</td>
                        <td>{{ author.email }}</td>
                        <td> {{ author.nbBooks }}</td>
                        <td>
                            <!-- Add action buttons here if needed -->
                            <a href="{{ path('author_edit', {'id': author.id}) }}">Edit</a>
                            <form method="post" action="{{ path('author_delete', {'id': author.id}) }}" onsubmit="return confirm('Are you sure you want to delete this author?');" style="display:inline;">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ author.id) }}">
                                <button class="btn">Delete</button>
                            </form>

                        </td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <td>
                        <p>number of published books: {{ nb_published }}</p>
                        <p>number of published books: {{ nb_unpublished }}</p>
                    </td>
                </tr>
                <tr>
                    <td colspan="4">
                        <a href="{{ path('author_new') }}" class="btn btn-success">Add a new author</a>
                    </td>
                    <td colspan="4">
                        <a class="btn btn-primary" href="{{ path('app_book') }}">Show Books</a>
                    </td>
                </tr>
                </tfoot>
            </table>
            <form action="{{path('authorMinMax')}}">
                <input type="text" name="min" placeholder="min">
                <input type="text" name="max" placeholder="max">
                <button type="submit">submit</button>
            </form>
        {% endif %}

    </div>
{% endblock %}

templates/author/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add a new author{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="mb-4">Add a new author</h1>

        {{ form_start(form, {'attr': {'class': 'needs-validation', 'novalidate': 'novalidate'}}) }}
        <div class="form-group row mb-3">
            {{ form_label(form.username, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
            <div class="col-sm-10">
                {{ form_widget(form.username, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="form-group row mb-3">
            {{ form_label(form.email, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
            <div class="col-sm-10">
                {{ form_widget(form.email, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <div class="form-group row mb-3">
            {{ form_label(form.nb_books, null, {'label_attr': {'class': 'col-sm-2 col-form-label'}}) }}
            <div class="col-sm-10">
                {{ form_widget(form.nb_books, {'attr': {'class': 'form-control'}}) }}
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Add Author</button>
        {{ form_end(form) }}
    </div>
{% endblock %}

templates/author/success.html.twig
{% extends 'base.html.twig' %}

{% block title %}Success{% endblock %}

{% block body %}
    <div class="container mt-5">
        <div class="alert alert-success" role="alert">
            Author added successfully!
        </div>
    </div>
    <script>
        setTimeout(function() {
            window.location.href = "{{ path('app_author') }}";
        }, 5000);
    </script>
{% endblock %}